services:
  harvest:
    image: ghcr.io/centrefordigitalhumanities/dh-scrapers-iis:latest
    restart: unless-stopped
    volumes:
      - iis-files:/iis-files
      - epidoc-stylesheets:/epidoc-stylesheets
      - type: bind
        source: $OUTPUT_FOLDER
        target: /output
      - type: bind
        source: harvest-metadata
        target: /harvest-metadata
    command: sh /scripts/export-newest.sh
  parse:
    image: ghcr.io/centrefordigitalhumanities/dh-scrapers:latest
    restart: unless-stopped
    depends_on:
      harvest:
        condition: service_completed_successfully
    volumes:
      - iis-files:/iis-files
      - type: bind
        source: $OUTPUT_FOLDER
        target: /output
      - type: bind
        source: .
        target: /dh-scrapers/iis
    stdin_open: true
    tty: true
    command: python -m iis --import_folder /iis-files --export_folder /output
  postprocess:
    image: atomgraph/saxon
    restart: unless-stopped
    platform: linux/amd64
    depends_on:
      parse:
        condition: service_completed_successfully
    volumes:
      - epidoc-stylesheets:/xsl
      - type: bind
        source: $OUTPUT_FOLDER
        target: /output
      - type: bind
        source: $OUTPUT_POSTPROCESSED
        target: /postprocessed
    command: -s:/output -xsl:/xsl/start-txt.xsl -o:/postprocessed

volumes:
  iis-files:
  epidoc-stylesheets: