FROM docker.io/library/python:alpine

ENV PYTHONUNBUFFERED=1

# equals a mkdir and a cd
WORKDIR /dh-scrapers

COPY ./base_scraper /dh-scrapers/base_scraper
COPY ./utilities /dh-scrapers/utilities
COPY requirements.txt /dh-scrapers
# copy python module
COPY ./iis /dh-scrapers/iis

RUN pip install --upgrade pip
RUN pip install -r requirements.txt
# to fix the urllib3 version error (see: https://stackoverflow.com/questions/78163280/no-module-named-urllib3-packages-six-moves)
RUN pip install requests --upgrade && pip install urllib3 --upgrade
RUN chmod -R g+rwx /dh-scrapers # rootless
