FROM docker.io/library/alpine

RUN apk add --no-cache git
RUN git config --system --add safe.directory '*' # rootless

WORKDIR /epidoc-stylesheets
# the most recent version of Epidoc stylesheets fails with the saxon image
RUN git clone -b v9.5 --single-branch https://github.com/EpiDoc/Stylesheets .

WORKDIR /iip-texts
RUN git clone -n --depth=1 --filter=tree:0 \
https://github.com/Brown-University-Library/iip-texts/ .
RUN chmod -R g+rwx /iip-texts # rootless
# check out only the /epidoc-files directory
RUN git sparse-checkout set --no-cone /epidoc-files

COPY ./scripts/export-newest.sh /scripts/
RUN chmod -R g+rwx /scripts # rootless
