apiVersion: batch/v1
kind: Job
metadata:
  name: dh-scrapers-job
spec:
  template:
    spec:
      volumes:
      - name: shared-data
        emptyDir: {}
      - name: dh-scrapers-vol
        persistentVolumeClaim:
          claimName: dh-scrapers-pvc
      initContainers:
      - name: quicky
        image: busybox
        env:
          - name: RUNNER_TOKEN
            value: <ephemeral_runner_token>
        envFrom:
        - configMapRef:
            name: dh-scrapers-runner-cm
        command: ['sh', '-c', 'for i in 1 2 3; do echo "quicky `date`" >> /quicky-data/timeline.txt && sleep 30s; done;'] # 3*30s=90s=1.5m
        volumeMounts:
        - name: shared-data
          mountPath: /quicky-data
        - name: dh-scrapers-vol
          mountPath: /scrapers-data
      - name: crunchy
        image: busybox
        # command: ['sh', '-c', 'exit 1'] # kill -SIGHUP $$
        command: ['sh', '-c', 'for i in 1 2 3 4 5 6 7 8 9 10; do echo "crunchy `date`" >> /crunchy-data/timeline.txt && sleep 172800ss; done;'] # 10*17280s=172800s=2days
        volumeMounts:
        - name: shared-data
          mountPath: /crunchy-data
      containers:
      - name: initcons-done
        image: busybox
        command: ['sh', '-c', 'echo "Init containers completed" && cat /data/timeline.txt']
        volumeMounts:
        - name: shared-data
          mountPath: /data
      restartPolicy: Never
  backoffLimit: 0

# Init containers completed
# quicky Thu May 1 13:09:32 UTC 2025
# quicky Thu May 1 13:10:02 UTC 2025
# quicky Thu May 1 13:10:32 UTC 2025
# crunchy Thu May 1 13:11:04 UTC 2025
# crunchy Thu May 1 17:59:04 UTC 2025
# crunchy Thu May 1 22:47:04 UTC 2025
# crunchy Fri May 2 03:35:04 UTC 2025
# crunchy Fri May 2 08:23:04 UTC 2025
# crunchy Fri May 2 13:11:04 UTC 2025
# crunchy Fri May 2 17:59:04 UTC 2025
# crunchy Fri May 2 22:47:04 UTC 2025
# crunchy Sat May 3 03:35:04 UTC 2025
# crunchy Sat May 3 08:23:04 UTC 2025
# │     Command:                                                                                                                                                                         │
# │       sh                                                                                                                                                                             │
# │       -c                                                                                                                                                                             │
# │       exit 1                                                                                                                                                                         │
# │     State:          Terminated                                                                                                                                                       │
# │       Reason:       Error                                                                                                                                                            │
# │       Exit Code:    1                                                                                                                                                                │
# │       Started:      Wed, 07 May 2025 10:53:27 +0200                                                                                                                                  │
# │       Finished:     Wed, 07 May 2025 10:53:27 +0200                                                                                                                                  │
# │     Ready:          False                                                                                                                                                            │
# │     Restart Count:  0