apiVersion: batch/v1
kind: Job
metadata:
  name: dh-scrapers-job
spec:
  template:
    spec:
      volumes:
      - name: dh-scrapers-vol
        persistentVolumeClaim:
          claimName: dh-scrapers-pvc
      - name: dh-scrapers-secret
        secret:
          secretName: elasticsearch-apikey
      initContainers:
      - name: timestamped-directory
        image: busybox
        volumeMounts:
        - name: dh-scrapers-vol
          mountPath: /current_run # on Pod
          subPath: current_run # inside PVC
        command: ['sh', '-c', 'DIR_STAMP=$(date +%Y%m%d_%H%M%S); mkdir /current_run/$DIR_STAMP; echo "$DIR_STAMP" > /current_run/is-scraping; cat /current_run/is-scraping']
      - name: dh-scrapers-iis # here attach!!!!
        image: ghcr.io/centrefordigitalhumanities/dh-scrapers-iis:latest
        volumeMounts:
        - name: dh-scrapers-vol
          mountPath: /iis-harvester-data # on Pod
          subPath: current_run # inside PVC
        command: ['ls', '-larth','/scripts']
      - name: echoes-from-the-sea
        image: busybox
        envFrom:
        - configMapRef:
            name: dh-scrapers-cm
        volumeMounts:
        - name: dh-scrapers-secret
          mountPath: "/secrets"
          readOnly: true
        command: ['sh', '-c', 'cat /secrets/elastic-apikey; echo $FAV_FRUIT;']
      - name: fill-move-delete
        image: busybox
        volumeMounts:
        - name: dh-scrapers-vol
          mountPath: /current_run
          subPath: current_run
        - name: dh-scrapers-vol
          mountPath: /previous_runs
          subPath: previous_runs
        command: ['sh', '-c', 'DIR_STAMP=$(cat /current_run/is-scraping); echo "apple" >> /current_run/$DIR_STAMP/basket.txt; echo "peach" >> /current_run/$DIR_STAMP/basket.txt; cat /current_run/$DIR_STAMP/basket.txt; mv /current_run/$DIR_STAMP /previous_runs/; rm /current_run/is-scraping']
      - name: number-crunch2timeline
        image: busybox
        volumeMounts:
        - name: dh-scrapers-vol
          mountPath: /crunch-data
        # command: ['sh', '-c', 'exit 1'] # kill -SIGHUP $$
        command: ['sh', '-c', 'for i in 1 2 3 4 5 6 7 8 9 10; do echo "chomp `date`" >> /crunch-data/timeline.txt && sleep 3s; done;'] # 10*17280s=172800s=2days
      containers:
      - name: initcons-done
        image: busybox
        command: ['sh', '-c', 'echo "Init containers completed" && cat /scrapers_data/timeline.txt; rm /scrapers_data/timeline.txt; ls /scrapers_data/previous_runs']
        volumeMounts:
        - name: dh-scrapers-vol
          mountPath: /scrapers_data
      restartPolicy: Never
  backoffLimit: 0
