apiVersion: batch/v1
kind: Job
metadata:
  name: dh-scrapers-job
spec:
  template:
    spec:
      volumes:
      - name: dh-scrapers-vol
        persistentVolumeClaim:
          claimName: dh-scrapers-pvc
      - name: dh-scrapers-secret
        secret:
          secretName: elasticsearch-apikey
      initContainers:
      - name: echoes-from-the-sea
        image: busybox
        envFrom:
        - configMapRef:
            name: dh-scrapers-cm
        volumeMounts:
        - name: dh-scrapers-vol
          mountPath: /scrapers-data
        - name: dh-scrapers-secret
          mountPath: "/secrets"
          readOnly: true
        command: ['sh', '-c', 'cat /secrets/elastic-apikey; echo $FAV_FRUIT;']
      - name: dir-tree
        image: busybox
        volumeMounts:
        - name: dh-scrapers-vol
          mountPath: /scrapers-data
        command: ['sh', '-c', 'mkdir']
      - name: fill-n-empty
        image: busybox
        volumeMounts:
        - name: dh-scrapers-vol
          mountPath: /scrapers-data
        command: ['sh', '-c', 'echo "apple" >> /scrapers-data/basket.txt; echo "peach" >> /scrapers-data/basket.txt; cat /scrapers-data/basket.txt; > /scrapers-data/fruits.txt; cat /scrapers-data/basket.txt']
      - name: number-crunch-timeline
        image: busybox
        volumeMounts:
        - name: dh-scrapers-vol
          mountPath: /crunch-data
        # command: ['sh', '-c', 'exit 1'] # kill -SIGHUP $$
        command: ['sh', '-c', 'for i in 1 2 3 4 5 6 7 8 9 10; do echo "chomp `date`" >> /crunch-data/timeline.txt && sleep 3s; done;'] # 10*17280s=172800s=2days
      containers:
      - name: initcons-done
        image: busybox
        command: ['sh', '-c', 'echo "Init containers completed" && cat /scrapers-data/timeline.txt']
        volumeMounts:
        - name: dh-scrapers-vol
          mountPath: /scrapers-data
      restartPolicy: Never
  backoffLimit: 0
