apiVersion: batch/v1
kind: Job
metadata:
  name: dh-scrapers-job
spec:
  template:
    spec:
      volumes:
      - name: dh-scrapers-vol
        persistentVolumeClaim:
          claimName: dh-scrapers-pvc
      - name: dh-scrapers-secret
        secret:
          secretName: elasticsearch-apikey
      initContainers:
      - name: echoes-from-the-sea
        image: busybox
        envFrom:
        - configMapRef:
            name: dh-scrapers-cm
        volumeMounts:
        - name: dh-scrapers-vol
          mountPath: /scrapers_data
        - name: dh-scrapers-secret
          mountPath: "/secrets"
          readOnly: true
        command: ['sh', '-c', 'cat /secrets/elastic-apikey; echo $FAV_FRUIT;']
      - name: directory-tree
        image: busybox
        volumeMounts:
        - name: dh-scrapers-vol
          mountPath: /scrapers_data
        command: ['sh', '-c', 'DIR_STAMP=$(date +%Y%m%d_%H%M%S); mkdir /scrapers_data/old_runs; mkdir -p /scrapers_data/current_run/$DIR_STAMP; echo "$DIR_STAMP" > /scrapers_data/current_run/is-scraping; cat /scrapers_data/current_run/is-scraping']
      - name: fill-move-delete
        image: busybox
        volumeMounts:
        - name: dh-scrapers-vol
          mountPath: /scrapers_data
        command: ['sh', '-c', 'DIR_STAMP=$(< /scrapers_data/current_run/is-scraping); echo "apple" >> /scrapers_data/current_run/$DIR_STAMP/basket.txt; echo "peach" >> /scrapers_data/current_run/$DIR_STAMP/basket.txt; cat /scrapers_data/current_run/$DIR_STAMP/basket.txt; mv /scrapers_data/current_run/$DIR_STAMP /scrapers_data/old_runs/; rm /scrapers_data/current_run/is-scraping']
      - name: number-crunch-timeline
        image: busybox
        volumeMounts:
        - name: dh-scrapers-vol
          mountPath: /crunch-data
        # command: ['sh', '-c', 'exit 1'] # kill -SIGHUP $$
        command: ['sh', '-c', 'for i in 1 2 3 4 5 6 7 8 9 10; do echo "chomp `date`" >> /crunch-data/timeline.txt && sleep 3s; done;'] # 10*17280s=172800s=2days
      containers:
      - name: initcons-done
        image: busybox
        command: ['sh', '-c', 'echo "Init containers completed" && cat /scrapers_data/timeline.txt; ls /scrapers_data/old_runs; ls /scrapers_data/current_run']
        volumeMounts:
        - name: dh-scrapers-vol
          mountPath: /scrapers_data
      restartPolicy: Never
  backoffLimit: 0
