apiVersion: batch/v1
kind: Job
metadata:
  name: harvest-job
spec:
  template:
    spec:
      volumes:
      - name: shared-data
        emptyDir: {}
      initContainers:
      - name: quicky
        image: busybox
        command: ['sh', '-c', 'for i in 1 2 3; do echo "quicky `date`" >> /quicky-data/timeline.txt && sleep 30s; done;'] # 3*30s=90s=1.5m
        volumeMounts:
        - name: shared-data
          mountPath: /quicky-data
      - name: crunchy
        image: busybox
        command: ['sh', '-c', 'for i in 1 2 3 4 5 6 7 8 9 10}; do echo "crunchy `date`" >> /crunchy-data/timeline.txt && sleep 1s; done;'] # 100*1728s=172800s=2days
        volumeMounts:
        - name: shared-data
          mountPath: /crunchy-data
      containers:
      - name: initcons-done
        image: busybox
        command: ['sh', '-c', 'echo "Init containers completed" && cat /data/timeline.txt']
        volumeMounts:
        - name: shared-data
          mountPath: /data
      restartPolicy: Never