apiVersion: batch/v1
kind: Job
metadata:
  name: harvest-job
spec:
  template:
    spec:
      containers:
      - name: ubuntu
        image: ubuntu
        command: ["/bin/sh"]
        args: ["-c", "for i in {1..10}; do echo 'Hello crunchy world!' >> /proc/1/fd/1; sleep 17280; done"]
        # logger()
        #- echo "hello I am crunching" >> /proc/1/fd/1
        #- sleep
        #- "2d"
      restartPolicy: OnFailure