apiVersion: batch/v1
kind: Job
metadata:
  name: harvest-job
spec:
  template:
    spec:
      containers:
      - name: ubuntu
        image: ubuntu
        args:
        - echo hello I am crunching >> /proc/1/fd/1
        - sleep
        - "2d"
      restartPolicy: OnFailure