apiVersion: batch/v1
kind: Job
metadata:
  name: harvest-job
spec:
  template:
    spec:
      initContainers:
      - name: initc1
        image: busybox
        command: ['sh', '-c', "for i in {1..100}; do sleep 1 && echo 'printy' ; done"]
      - name: initc2
        image: busybox
        command: ["/bin/sh"]
        args: ["-c", "for i in {1..100}; do echo 'Hello crunchy world!' >> /proc/1/fd/1; sleep 1728; done"] # 1728s*100=2days
      containers:
      - name: ubuntu
        image: ubuntu
        command: ['sh', '-c', "echo 'Init containers finished' && sleep 365d"]

      restartPolicy: Never #OnFailure
