apiVersion: batch/v1
kind: Job
metadata:
  name: harvest-job
spec:
  template:
    spec:
      containers:
      - name: ubuntu
        image: ubuntu
        command: ["/bin/sh"]
        args: ["-c", "for i in {1..100}; do echo 'Hello crunchy world!' >> /proc/1/fd/1; sleep 1728; done"] # two days
      restartPolicy: OnFailure