# This workflow will run every 3 months or manually

name: ScrapersFlow
run-name: ${{ github.actor }} is deploying scrapers
on: [push, workflow_dispatch]

jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
    -
      name: build-login-push
      uses: actions/checkout@v4
      uses: docker/setup-buildx-action@v3
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      uses: docker/build-push-action@v6
      with:
        context: iis/.
        file: iis/Dockerfile
        push: true
        tags: ghcr.io/centrefordigitalhumanities/dh-scrapers-iis:latest
        platforms: linux/amd64,linux/arm64
  deploy-scrapejob-to-kubernetes:
    runs-on: self-hosted
    env:
      KUBECTL_VERSION: v1.30.5
    steps:
    -
      name: Checkout code
      uses: actions/checkout@v4
    -
      name: Deploy with kubectl
      # apply kmanifests or leave them unchanged and always restart the deployment
      run: |
        curl -LO https://dl.k8s.io/release/$KUBECTL_VERSION/bin/linux/amd64/kubectl
        chmod +x ./kubectl
        ./kubectl apply -f ./kmanifests/dh-scrapers-cm.yaml --token=${{ secrets.SA_TOKEN }} --namespace gw-dev-rslab-peaceportal # create/modify
        ./kubectl delete job dh-scrapers-job --ignore-not-found=true --now --token=${{ secrets.SA_TOKEN }} --namespace gw-dev-rslab-peaceportal
        ./kubectl apply -f ./kmanifests/dh-scrapers-job.yaml --token=${{ secrets.SA_TOKEN }} --namespace gw-dev-rslab-peaceportal
      #./kubectl rollout restart deployment/kb-server --token=${{ secrets.SA_TOKEN }} --namespace gw-humit-sandbox