# This workflow will run every first of the month, to make sure we update the underlying images and libraries

# name: Build and push of all images

# on:
#     workflow_dispatch:
#     push:
#     schedule:
#     - cron: "0 0 1 * *"

# jobs:
#     build-scheduled:
#         name: Rebuild images
#         runs-on: ubuntu-latest
#         steps:
#         - uses: actions/checkout@v4
#         - name: Set up Docker Buildx
#           uses: docker/setup-buildx-action@v3
#         - name: Login to GitHub Container Registry
#           uses: docker/login-action@v3
#           with:
#             registry: ghcr.io
#             username: ${{ github.actor }}
#             password: ${{ secrets.GITHUB_TOKEN }}
#         - name: Build DH scrapers image
#           uses: docker/build-push-action@v6
#           with:
#             context: .
#             file: Dockerfile
#             push: true
#             tags: ghcr.io/centrefordigitalhumanities/dh-scrapers:latest
#             platforms: linux/amd64,linux/arm64
#         - name: Build iis image
#           uses: docker/build-push-action@v6
#           with:
#             context: iis/.
#             file: iis/Dockerfile
#             push: true
#             tags: ghcr.io/centrefordigitalhumanities/dh-scrapers-iis:latest
#             platforms: linux/amd64,linux/arm64

name: test-github-actions
run-name: ${{ github.actor }} is testing GitHub Actions
on: [push, workflow_dispatch]

jobs:
  check-bats-version:
    runs-on: self-hosted
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install -g bats
      - run: bats -v
      # Runs a set of commands using the runners shell
      - name: Run a one-line script
        run: echo Add other actions to build, test, and deploy your project.