# This workflow will run every first of the month, to make sure we update the underlying images and libraries

name: Build and push of all images

on:
    workflow_dispatch:
    push:
      paths:
        - Dockerfile
        - docker-compose.yaml
        - requirements.txt
    schedule:
        - cron: "0 0 1 * *"

jobs:
    build-scheduled:
        name: Rebuild images
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Build DH scrapers image
          uses: docker/build-push-action@v6
          with:
            context: .
            file: Dockerfile
            push: true
            tags: ghcr.io/centrefordigitalhumanities/dh-scrapers:latest
        - name: Build iis image
          uses: docker/build-push-action@v6
          with:
            context: iis/.
            file: iis/Dockerfile
            push: true
            tags: ghcr.io/centrefordigitalhumanities/dh-scrapers-iis:latest
        